# Generated by Django 5.2.7 on 2025-12-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('main', '0029_alter_bloggalleryimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.blogcategory',),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.blogpost',),
        ),
    ]
