# Generated by Django 5.2.9 on 2025-12-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(help_text='Use the editor to format your content.')),
                ('meta_description', models.CharField(blank=True, help_text='SEO Description', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True, help_text='Show this page link in the footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Texas Insurance Ratings', max_length=255)),
                ('site_email', models.EmailField(default='contact@example.com', max_length=254)),
                ('site_phone', models.CharField(default='(123) 456-7890', max_length=50)),
                ('site_address', models.TextField(default='708 Main Street\nHouston, TX 77002')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
