# Generated by Django 5.2.9 on 2025-12-28 07:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Title to display in the Hero section', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Meta Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Full clean editor with all options.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO Meta Description', max_length=160),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='This will be used as the page name and slug.', max_length=200),
        ),
    ]
