# Generated by Django 5.2.9 on 2025-12-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page_hero_title_page_meta_title_alter_page_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('legal', 'Legal'), ('company', 'Company'), ('resources', 'Resources')], default='legal', help_text='Section in the footer where this page should appear', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='copyright_text',
            field=models.CharField(default='© 2024 Texas Insurance Ratings. All rights reserved.', help_text='Footer copyright text', max_length=255),
        ),
    ]
