# Generated by Django 5.2.9 on 2025-12-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_page_category_siteconfiguration_copyright_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='home_page_description',
            field=models.TextField(default='Compare Texas Insurance Rates for Home, Auto, and Renters.', help_text='Meta description for the home page'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='home_page_title',
            field=models.CharField(default='Texas Insurance Ratings', help_text='Meta title for the home page', max_length=255),
        ),
    ]
