# Generated by Django 5.2.9 on 2025-12-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_siteconfiguration_home_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('company', 'Company'), ('legal', 'Legal')], default='company', help_text='Section in the footer where this page should appear', max_length=20),
        ),
    ]
