# Generated by Django 5.2.9 on 2025-12-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('resources', 'Resources'), ('company', 'Company'), ('legal', 'Legal')], default='resources', help_text='Section in the footer where this page should appear', max_length=20),
        ),
    ]
