# Generated by Django 5.2.9 on 2025-12-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='home_page_description',
            field=models.TextField(default='Compare Texas Insurance Rates for Home, Auto, and Renters.', help_text='Used for both SEO Meta Description and Hero Section Description'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='home_page_title',
            field=models.CharField(default='Texas Insurance Ratings', help_text='Used for both SEO Meta Title and Hero Section Title', max_length=255),
        ),
    ]
