# Generated by Django 5.2.9 on 2025-12-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_siteconfiguration_home_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='home_page_title',
            field=models.CharField(default="Compare <span class='text-[#ffcc00] italic'>Texas Insurance Rates</span>", help_text="Used for both SEO Meta Title and Hero Section Title. You can use HTML like <span class='text-[#ffcc00] italic'>text</span> for styling.", max_length=255),
        ),
    ]
