# Generated by Django 5.2.9 on 2025-12-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_siteconfiguration_home_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='home_page_title',
            field=models.CharField(default="Compare <span style='color: #ffcc00; font-style: italic;'>Texas Insurance Rates</span>", help_text="Used for both SEO Meta Title and Hero Section Title. Use <span style='color: #ffcc00; font-style: italic;'>text</span> for yellow italic styling.", max_length=255),
        ),
    ]
