# Generated by Django 5.2.9 on 2025-12-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_siteconfiguration_home_page_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Company & Legal Page', 'verbose_name_plural': 'Company & Legal Pages'},
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('company', 'Company'), ('legal', 'Legal')], default='company', help_text='Section in the footer where this page should appear', max_length=20),
        ),
    ]
