# Generated by Django 5.2.9 on 2025-12-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='has_dropdown',
            field=models.BooleanField(default=False, help_text='If checked, hovering this link will show latest 5 blog posts from this category'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='show_in_navbar',
            field=models.BooleanField(default=False, help_text='Show this category in the main navigation menu'),
        ),
    ]
