# Generated by Django 5.2.9 on 2025-12-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_blogpost_video_url_bloggalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional: Upload a video file from your device', null=True, upload_to='blog_videos/'),
        ),
    ]
