# Generated by Django 5.2.9 on 2025-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_blogpost_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='button_text',
            field=models.CharField(blank=True, help_text='Optional: Text for a Call-to-Action button', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='button_url',
            field=models.URLField(blank=True, help_text='Optional: URL for the Call-to-Action button', null=True),
        ),
    ]
