# Generated by Django 5.2.9 on 2025-12-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_blogpost_button_text_blogpost_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a parent category if this is a sub-category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.blogcategory'),
        ),
    ]
