# Generated by Django 5.2.9 on 2025-12-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='home_cta_text',
            field=models.CharField(blank=True, help_text='Button text for home page', max_length=200),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='home_cta_url',
            field=models.CharField(blank=True, help_text='Custom URL (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='home_description',
            field=models.TextField(blank=True, help_text='Description for home page'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='home_title',
            field=models.CharField(blank=True, help_text='Override name for home page display', max_length=100),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG code here'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='is_featured_on_home',
            field=models.BooleanField(default=False, help_text='Check to display this category on the home page top section'),
        ),
    ]
