# Generated by Django 5.2.9 on 2025-12-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_blogcategory_home_cta_text_blogcategory_home_cta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='home_sort_order',
            field=models.IntegerField(default=0, help_text='Order of display on home page'),
        ),
    ]
