# Generated by Django 5.2.9 on 2025-12-29

from django.db import migrations, models

COMPANIES = [
    ("Allstate", 1),
    ("State Farm", 3),
    ("Safeco", 4),
    ("Travelers", 5),
    ("Chubb", 6),
    ("Farmers", 8),
    ("Amica", 9),
    ("Liberty", 10),
    ("Nationwide", 12),
    ("AIG", 13),
    ("Texas Farm Bureau", 14),
    ("MetLife", 15),
    ("Mercury", 17),
    ("Foremost", 18),
    ("Auto Club", 19),
    ("Direct Auto Insurance", 21),
    ("USAA", 23),
    ("United Property", 24),
    ("Homesite", 25),
    ("Republic Lloyds", 30),
    ("Assurant", 31),
    ("Century National", 32),
    ("Esurance", 33),
    ("Allied", 34),
    ("Consolidated Lloyds", 35),
    ("Encompass", 36),
    ("Texas Windstorm Insurance", 37),
    ("Hartford", 38),
    ("Unitrin", 39),
    ("National Surety", 41),
]

def seed_brands(apps, schema_editor):
    InsurerBrand = apps.get_model('main', 'InsurerBrand')
    for name, ranking in COMPANIES:
        obj, _ = InsurerBrand.objects.get_or_create(name=name)
        obj.ranking = ranking
        obj.is_active = True
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_insurerbrand_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurerbrand',
            name='ranking',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insurerbrand',
            name='complaint_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurerbrand',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(seed_brands, migrations.RunPython.noop),
    ]

