# Generated by Django 5.2.9 on 2025-12-29

from django.db import migrations
from django.utils.text import slugify

COMPANIES = [
    "Allstate",
    "State Farm",
    "Safeco",
    "Travelers",
    "Chubb",
    "Farmers",
    "Amica",
    "Liberty",
    "Nationwide",
    "AIG",
    "Texas Farm Bureau",
    "MetLife",
    "Mercury",
    "Foremost",
    "Auto Club",
    "Direct Auto Insurance",
    "USAA",
    "United Property",
    "Homesite",
    "Republic Lloyds",
    "Assurant",
    "Century National",
    "Esurance",
    "Allied",
    "Consolidated Lloyds",
    "Encompass",
    "Texas Windstorm Insurance",
    "Hartford",
    "Unitrin",
    "National Surety",
]

def seed_categories(apps, schema_editor):
    BlogCategory = apps.get_model('main', 'BlogCategory')
    # Create or get parent 'companies'
    parent, _ = BlogCategory.objects.get_or_create(name='companies', defaults={'description': 'All insurance companies'})
    # Ensure parent has no parent
    parent.parent = None
    # Ensure unique slug for parent
    base_slug = slugify('companies')
    slug = base_slug
    i = 1
    while BlogCategory.objects.filter(slug=slug).exclude(pk=parent.pk).exists():
        slug = f'{base_slug}-{i}'
        i += 1
    parent.slug = slug
    parent.save()
    # Create subcategories
    for name in COMPANIES:
        sub, _ = BlogCategory.objects.get_or_create(name=name, parent=parent)
        base_slug = slugify(name)
        slug = base_slug
        i = 1
        while BlogCategory.objects.filter(slug=slug).exclude(pk=sub.pk).exists():
            slug = f'{base_slug}-{i}'
            i += 1
        sub.slug = slug
        sub.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_insurerbrand_fields_and_seed'),
    ]

    operations = [
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
