# Generated by Django 5.2.9 on 2025-12-29

from django.db import migrations, models

def set_defaults(apps, schema_editor):
    InsurerBrand = apps.get_model('main', 'InsurerBrand')
    for b in InsurerBrand.objects.all():
        if b.show_in_companies is None:
            b.show_in_companies = True
        if b.show_on_home is None:
            b.show_on_home = False
        b.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_seed_companies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurerbrand',
            name='show_in_companies',
            field=models.BooleanField(default=True, help_text='Show in Companies categories/table'),
        ),
        migrations.AddField(
            model_name='insurerbrand',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Show brand on home/start page logos'),
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop),
    ]

