# Generated by Django 5.2.9 on 2025-12-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_insurerbrand_visibility_flags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurerbrand',
            options={'ordering': ['ranking', 'name'], 'verbose_name': 'Insurer Brand', 'verbose_name_plural': 'Insurer Brands'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='wizard_final_screenshot_url',
            field=models.URLField(blank=True, help_text='URL of the final quotes screenshot shown after wizard completion', null=True),
        ),
        migrations.AlterField(
            model_name='insurerbrand',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars', null=True),
        ),
    ]
