# Generated by Django 5.2.9 on 2025-12-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_insurerbrand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('premium', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('cta_text', models.CharField(default='Call Now', max_length=100)),
                ('cta_url', models.URLField(blank=True)),
                ('highlight', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='main.insurerbrand')),
            ],
            options={
                'verbose_name': 'Quote Offer',
                'verbose_name_plural': 'Quote Offers',
                'ordering': ['order', 'id'],
            },
        ),
    ]
