# Generated by Django 5.2.9 on 2025-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_quoteoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteoffer',
            name='brand',
        ),
        migrations.AddField(
            model_name='quoteoffer',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='offers', to='main.insurerbrand'),
        ),
    ]
